async function runTests() {
  console.log("=== STARTING API TESTS ===");

  try {
    // 1. Test Notice API
    console.log("\n--- Testing Notices API ---");
    const newNotice = {
      title: "Test Notice: Holiday Announcement",
      category: "Holidays",
      content: "This is a test notice generated by the automated testing script.",
      isPinned: true,
      date: new Date().toISOString()
    };
    
    let res = await fetch('http://localhost:5000/api/notices', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(newNotice)
    });
    let data = await res.json();
    console.log("POST /api/notices Status:", res.status, data.status);
    const noticeId = data.data._id;

    res = await fetch('http://localhost:5000/api/notices');
    data = await res.json();
    console.log("GET /api/notices Status:", res.status, "Count:", data.count);
    
    // 2. Test Results API
    console.log("\n--- Testing Results API ---");
    const newResult = {
      title: "Test Result: Class 10 EM Topper",
      academicYear: "2025-26",
      classLevel: "10 EM",
      imageSrc: "https://via.placeholder.com/150",
      isArchived: false
    };

    res = await fetch('http://localhost:5000/api/results', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(newResult)
    });
    data = await res.json();
    console.log("POST /api/results Status:", res.status, data.status);
    const resultId = data.data._id;

    res = await fetch('http://localhost:5000/api/results');
    data = await res.json();
    console.log("GET /api/results Status:", res.status, "Count:", data.data.length);

    // 3. Test Inquiries API
    console.log("\n--- Testing Inquiries API ---");
    const newInquiry = {
      studentName: "Test Student",
      parentName: "Test Parent",
      phone: "+91 99999 99999",
      email: "test@example.com",
      class: "Class 1-5",
      message: "Testing the admission inquiry form."
    };

    res = await fetch('http://localhost:5000/api/inquiries', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(newInquiry)
    });
    data = await res.json();
    console.log("POST /api/inquiries Status:", res.status, data.status);
    const inquiryId = data.data._id;

    res = await fetch('http://localhost:5000/api/inquiries');
    data = await res.json();
    console.log("GET /api/inquiries Status:", res.status, "Count:", data.count);

    // 4. Cleanup (Testing DELETE)
    console.log("\n--- Cleaning up Test Data ---");
    res = await fetch(`http://localhost:5000/api/notices/${noticeId}`, { method: 'DELETE' });
    console.log("DELETE /api/notices Status:", res.status);

    res = await fetch(`http://localhost:5000/api/results/${resultId}`, { method: 'DELETE' });
    console.log("DELETE /api/results Status:", res.status);

    res = await fetch(`http://localhost:5000/api/inquiries/${inquiryId}`, { method: 'DELETE' });
    console.log("DELETE /api/inquiries Status:", res.status);

    console.log("\n=== ALL TESTS PASSED SUCCESSFULLY ===");

  } catch (error) {
    console.error("Test execution failed:", error);
  }
}

runTests();
